public:
  proxy:
    url: http://localhost:3000/
  googleAnalytics:
    UA: 'UA-73432166-1'
  contact:
    email: 'evenements@snvel.fr'
    defaultSubject: "Evènements SNVEL - Demande d'informations"
