mail:
  build: mail
  log_driver: "json-file"
  volumes:
  - ./postfix:/tmp/postfix/
  hostname: mail
  domainname: pem.paris
  ports:
  # SMTP
  - "192.168.1.50:25:25"
  - "192.168.1.50:25:25/udp"

# Persistence layer: Mongo
mongo:
  build: mongo
  volumes:
    - /var/db:/db
  expose:
    - "27017"

# Application server: NodeJS (Meteor)
meteor:
  build: meteor
  log_driver: "json-file"
  links:
    - mongo
  environment:
    MONGO_URL: "mongodb://mongo:27017"
    MONGO_OPLOG_URL: "mongodb://mongo:27017/local"
    PORT: 3000
    ROOT_URL: "https://dev.pem.paris"
  volumes:
    - /etc/meteor:/etc/meteor
  expose:
    - "3000"

# Front layer, static file, SSL, proxy cache: NGinx
nginx:
  build: nginx
  log_driver: "json-file"
  links:
    - meteor
  environment:
    # Can be: dev, pre, prod
    HOST_TARGET: "pre"
  volumes:
    - /etc/certs:/etc/certs
    - /var/cache:/var/cache
    - /var/tmp:/var/tmp
  ports:
    - "80:80"
    - "443:443"
