# Persistence layer: Mongo
mongo:
  image: pemarchandet/evenements-snvel-mongo:v1.0.0
  extends:
    file: common.yml
    service: mongo
  restart: always

# Application server: NodeJS (Meteor)
meteor:
  image: pemarchandet/evenements-snvel-meteor:v1.1.0
  extends:
    file: common.yml
    service: meteor
  links:
    - mongo
  environment:
    ROOT_URL: "https://evenements-snvel.fr"
  restart: always

# Front layer, static file, SSL, proxy cache: NGinx
nginx:
  image: pemarchandet/evenements-snvel-nginx:v1.1.0
  extends:
    file: common.yml
    service: nginx
  links:
    - meteor
  environment:
    # Can be: dev, pre, prod
    HOST_TARGET: "prod"
  restart: always
