# Persistence layer: Mongo
mongo:
  extends:
    file: common.yml
    service: mongo

# Application server: NodeJS (Meteor)
meteor:
  extends:
    file: common.yml
    service: meteor
  links:
    - mongo
  environment:
    ROOT_URL: "https://dev.pem.paris"

# Front layer, static file, SSL, proxy cache: NGinx
nginx:
  extends:
    file: common.yml
    service: nginx
  links:
    - meteor
  environment:
    # Can be: dev, pre, prod
    HOST_TARGET: "pre"

dns:
  build: dns
  log_driver: "json-file"
  volumes:
    - /var/bind/:/var/bind/
  ports:
    - "192.168.1.50:53:53"
    - "192.168.1.50:53:53/udp"

mail:
  build: mail
  log_driver: "json-file"
  volumes:
  - ./postfix:/tmp/postfix/
  hostname: mail
  domainname: pem.paris
  ports:
  # SMTP
  - "192.168.1.50:25:25"
  - "192.168.1.50:25:25/udp"

mailcatcher:
  build: mailcatcher
  log_driver: "json-file"
  ports:
  # SMTP
  - "192.168.1.50:25:1025"
  - "192.168.1.50:25:1025/udp"
  # HTTP access
  - "192.168.1.50:8080:1080"
