dns:
  build: dns
  log_driver: "json-file"
  volumes:
    - /var/bind/:/var/bind/
  ports:
    - "192.168.1.50:53:53"
    - "192.168.1.50:53:53/udp"
mail:
  build: mail
  log_driver: "json-file"
  volumes:
  - ./spamassassin:/tmp/spamassassin/
  - ./postfix:/tmp/postfix/
  hostname: mail
  domainname: pem.paris
  ports:
  # SMTP
  - "192.168.1.50:25:25"
  - "192.168.1.50:25:25/udp"
  # SMTP over SSL
  - "192.168.1.50:587:587"
  - "192.168.1.50:587:587/udp"
  # - "143:143"
  # - "993:993"
