dns:
  build: dns
  log_driver: "json-file"
  volumes:
    - /var/bind/:/var/bind/
  ports:
    - "192.168.1.50:53:53"
    - "192.168.1.50:53:53/udp"

mail:
  build: mail
  log_driver: "json-file"
  volumes:
  - ./postfix:/tmp/postfix/
  hostname: mail
  domainname: pem.paris
  ports:
  # SMTP
  - "192.168.1.50:25:25"
  - "192.168.1.50:25:25/udp"

# Persistence layer: Mongo
mongo:
  build: mongo
  volumes:
    - /var/db:/db
  expose:
    - "27017"

# Application server: NodeJS (Meteor)
meteor:
  build: meteor
  log_driver: "json-file"
  links:
    - mongo
  environment:
    MONGO_URL: "mongodb://db:27017"
    MONGO_OPLOG_URL: "mongodb://db:27017/local"
    PORT: 3000
    ROOT_URL: "https://192.168.1.50"
  # expose:
  #   - "3000"
  ports:
  - "192.168.1.50:3000:3000"

# Front layer, static file, SSL, proxy cache: NGinx
nginx:
  build: nginx
  log_driver: "json-file"
  links:
    - meteor
  environment:
    # Can be: dev, pre, prod
    HOST_TARGET: "dev"
  volumes:
    - /etc/certs:/etc/certs
    - /var/cache:/var/cache
    - /var/tmp:/var/tmp
  ports:
    - "80:80"
    - "443:443"

mailcatcher:
  build: mailcatcher
  log_driver: "json-file"
  ports:
  # SMTP
  - "192.168.1.50:25:1025"
  - "192.168.1.50:25:1025/udp"
  # HTTP access
  - "192.168.1.50:8080:1080"
